### ISSUE TITLE
Initial project scaffolding.

### ISSUE THREAD

**Issue by triedal** [obsydian-constructs/hermes-ui#1]
Hi guys, this repo is going to be for the job application UI. This is the application that will be used by the job applicant, not the recruiter. We've all agreed that this will be a React/Redux application. We will need to scaffold this out so we can begin development.

**Comment by triedal** [comment]
@stew1 had suggested we use [create-react-app](https://github.com/facebookincubator/create-react-app).

@rynatk any suggestions?

**Comment by rynatk** [comment]
@triedal I'm cool with that
